### ISSUE TITLE
Remove non-functional styles

### ISSUE THREAD

**Issue by christopher-baek** [kristiw52/my-one-page-website#2]
- The `background-size` and `background-attachment` properties are only needed when you have a background image. These should be removed: 
  - https://github.com/kristiw52/my-one-page-website/blob/2fc1f09601ede8b8f6ac2576278a8493fef5ef03/css/main.css#L62-L63

- The `header` tag is already pretty unique, so it doesn't need the extra class.
  - https://github.com/kristiw52/my-one-page-website/blob/2fc1f09601ede8b8f6ac2576278a8493fef5ef03/index.html#L32
- The selector for the styling can be updated to just target the `header` tag, similar to what you did for your `footer` styling. The `header` tag should also inherently have a `display` value of `block` (http://www.w3schools.com/tags/tag_header.asp).
  - https://github.com/kristiw52/my-one-page-website/blob/2fc1f09601ede8b8f6ac2576278a8493fef5ef03/css/main.css#L66-L70

- This is not doing anything right now, so the styling and corresponding class should be removed.
  - https://github.com/kristiw52/my-one-page-website/blob/2fc1f09601ede8b8f6ac2576278a8493fef5ef03/css/main.css#L89-L91
  - https://github.com/kristiw52/my-one-page-website/blob/2fc1f09601ede8b8f6ac2576278a8493fef5ef03/index.html#L46

- The mobile styling should be removed until it is needed (https://en.wikipedia.org/wiki/You_aren't_gonna_need_it).
  - https://github.com/kristiw52/my-one-page-website/blob/2fc1f09601ede8b8f6ac2576278a8493fef5ef03/css/main.css#L97-L113

**Comment by kristiw52** [comment]
I made the changes and just sent you a pull request to review.

Thanks

On Dec 2, 2016, at 4:54 PM, Christopher Baek <notifications@github.com<mailto:notifications@github.com>> wrote:


  *   The background-size and background-attachment properties are only needed when you have a background image. These should be removed:

     *   https://github.com/kristiw52/my-one-page-website/blob/2fc1f09601ede8b8f6ac2576278a8493fef5ef03/css/main.css#L62-L63
  *   The header tag is already pretty unique, so it doesn't need the extra class.

     *   https://github.com/kristiw52/my-one-page-website/blob/2fc1f09601ede8b8f6ac2576278a8493fef5ef03/index.html#L32
  *   The selector for the styling can be updated to just target the header tag, similar to what you did for your footer styling. The header tag should also inherently have a display value of block (http://www.w3schools.com/tags/tag_header.asp).

     *   https://github.com/kristiw52/my-one-page-website/blob/2fc1f09601ede8b8f6ac2576278a8493fef5ef03/css/main.css#L66-L70
  *   This is not doing anything right now, so the styling and corresponding class should be removed.

     *   https://github.com/kristiw52/my-one-page-website/blob/2fc1f09601ede8b8f6ac2576278a8493fef5ef03/css/main.css#L89-L91
     *   https://github.com/kristiw52/my-one-page-website/blob/2fc1f09601ede8b8f6ac2576278a8493fef5ef03/index.html#L46
  *   The mobile styling should be removed until it is needed (https://en.wikipedia.org/wiki/You_aren't_gonna_need_it).

     *   https://github.com/kristiw52/my-one-page-website/blob/2fc1f09601ede8b8f6ac2576278a8493fef5ef03/css/main.css#L97-L113

-

**Comment by christopher-baek** [comment]
Looks good
